### ISSUE TITLE
In the c++ version of the interpreter

### ISSUE THREAD

**Issue by One916** [hostilefork/whitespacers#12]
In inter.cpp Vm::buildLabels() Line 223:
`assert( labels.find(l->label) == labels.end() );`
I should delete this row otherwise no program would run(and give me a assert-failure)!!!

**Comment by hostilefork** [comment]
Sorry to miss this issue, I had not been monitoring this, and only came back to it recently.

So I have good news: Someone *is* paying attention... there is a larger "whitespace corpus" project:

https://github.com/wspace/corpus

He's putting it together with tests and making sure everyone can actually run the interpreters, so please see wherever the C++ versions over there are at if this (or other) comments are relevant.

Apologies again for overlooking your issue.
