### ISSUE TITLE
Adding new language implementation

### ISSUE THREAD

**Issue by derek121** [hostilefork/whitespacers#7]
I wrote a Whitespace interpreter in Erlang, which I just presented at an Erlang/Elixir conference in San Francisco. Curious about opening PRs for adding it here. Seems like the procedure is to copy my code into a fork of this repo and do the PR. What about just adding an `erlang/` dir, which has a file with a link to my repo. If I was to update my code later, I'd have to then update this repo as well.

Has this question come up before?

**Comment by hostilefork** [comment]
Becoming the de-facto maintainer of whitespace language implementations is an odd business.

It's up to you.  And if you have ideas on how to do it better, I'm all ears...as this is notoriously unprofitable work for me.  :-)

If you would like to do it with a submodule, fine.  If you would like to do it without a submodule, fine.  If you would like to join up and take responsibility for random internet requests like yours here, also fine.  :-)

**Comment by derek121** [comment]
Cool, yeah, just don't want to violate whatever norms have been established. Guess I'll add a link to my repo, so wouldn't have to update things in 2 places should I change things in the future.

I gave a 5 minute lightning talk on my implementation at the conf today, and got a good laugh at the start when I said how only space, tab, and linefeed are significant in Whitespace. :)

**Comment by hostilefork** [comment]
You might be amused by:

http://uscii.hostilefork.com/

**Comment by derek121** [comment]
Damn, that's wild, thanks. :)

**Comment by derek121** [comment]
This slide got a good laugh:
<img width="1170" alt="whitespace-basic-program" src="https://cloud.githubusercontent.com/assets/1594587/24278757/f7558456-1002-11e7-9ab1-938e4462ab78.png">
